spring.application.name=monitoring-app
server.port=8080
#métriques
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
#logs et écriture des logs dans un fichier dédié
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.file.name=/var/log/spring/monitoring-app.log
