events {}

http {

  access_log /dev/stdout;
  error_log /dev/stderr;

  server {
    listen 80;

    location / {
      return 200 'nginx ok';
      add_header Content-Type text/plain;
    }
  }

  server {
    listen 8082;

    location = /stub_status {
      stub_status;
      allow all;
    }
  }
}
