[monitored_vms]
appscript ansible_host=10.10.10.56 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/appscript_key

[monitoring_server]
monitoring ansible_host=10.10.10.50 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/monitoring_key

[other_vms]
os-linux             ansible_host=10.10.10.51 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/os-linux_key
webserver            ansible_host=10.10.10.52 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/webserver_key
database             ansible_host=10.10.10.53 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/database_key
nosql                ansible_host=10.10.10.54 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/nosql_key
appjava              ansible_host=10.10.10.55 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/appjava_key
application-services ansible_host=10.10.10.57 ansible_user=vagrant ansible_ssh_private_key_file=~/projet_PFE/keys/application-services_key

[all_vms:children]
monitored_vms
monitoring_server
other_vms
